EW24-9-realiser-une-sequence-doperations
btssn-lasalle-84/ergonomic-workstation-2024 pull request #14
Opened 2024-05-29 17:37 UTC by gavril1

2024-05-29 17:52 UTC, tvaira requested changes

2024-05-29 17:52 UTC, tvaira commented on ergonomic-workstation-rpi/processusassemblage.cpp
> +    qDebug() << Q_FUNC_INFO << "méthode exéctutée";
C'est quoi ce `qDebug()` !!!!!!!!!!!!!!!!!!!

2024-05-29 17:52 UTC, tvaira commented on ergonomic-workstation-rpi/processusassemblage.cpp
> +    return this->nom;
Il n'y a pas d'attribut `nom` ! Il se nomme `nomProcessus` !

2024-05-29 17:52 UTC, tvaira commented on ergonomic-workstation-rpi/processusassemblage.cpp
> +    qDebug() << "nom" << nom;
Il n'a aucune chance de s'exécuter après un `return` !!!!!!!!!!!!!!!!!!!!!!!

2024-05-29 17:52 UTC, tvaira commented on ergonomic-workstation-rpi/processusassemblage.h
> +    int     getNbPieces();
`const` ?!

2024-05-30 10:03 UTC, tvaira requested changes

2024-05-30 10:03 UTC, tvaira commented on ergonomic-workstation-rpi/processusassemblage.h
>      int             nbBacs;
Ce n'est pas un attribut !

2024-05-30 10:03 UTC, tvaira commented on ergonomic-workstation-rpi/processusassemblage.h
> +    int             idBac;
Ce n'est pas un attribut !

2024-05-30 10:03 UTC, tvaira commented on ergonomic-workstation-rpi/processusassemblage.h
>      QDialog*        dialog;
????

2024-05-30 10:03 UTC, tvaira commented on ergonomic-workstation-rpi/processusassemblage.h
> +    QString         nomPiece;
Ce ne sont pas des attributs !

2024-05-30 10:03 UTC, tvaira commented on ergonomic-workstation-rpi/processusassemblage.cpp
> +            bacUtilise.push_back(idBac);
Je ne pense pas ! Il y a une classe `Bac` et il y aura donc des objets de type `Bac`

2024-05-30 10:04 UTC, tvaira requested changes

2024-05-30 10:04 UTC, tvaira commented on ergonomic-workstation-rpi/processusassemblage.cpp
>              nomImagePiece =
Ce sont des variables locales !

2024-05-30 11:55 UTC, tvaira requested changes

2024-05-30 11:55 UTC, tvaira commented on ergonomic-workstation-rpi/processusassemblage.cpp
> +            bacUtilise.push_back(new Bac(idBac, nomPiece, nbPieces, nomImage));
Ce n'est pas `nomImage` mais `nomImagePiece`

2024-05-30 11:55 UTC, tvaira commented on ergonomic-workstation-rpi/processusassemblage.h
>      QDialog*        dialog;
C'est quoi ce `dialog` ???????????!!!!!!!!!!!!!!!!!!

2024-05-30 11:56 UTC, tvaira requested changes

2024-05-30 11:56 UTC, tvaira commented on ergonomic-workstation-rpi/processusassemblage.cpp
>          nomOperation       = configurationProcessusAssemblage.value(nomSection + "/nom").toString();
Ce n'est pas `nomOperation` ?!

2024-06-04 15:58 UTC, tvaira requested changes

2024-06-04 15:58 UTC, tvaira commented on ergonomic-workstation-rpi/affichagepageprocessus.cpp
>      // @todo transformer le QLabel en QTextBrowser pour commentairesOperation
Faudrait peut-être enlever les todos ???

2024-06-04 15:58 UTC, tvaira commented on ergonomic-workstation-rpi/affichagepageprocessus.cpp
> +    choixBouton(0), cheminRacineProcessusAssemblage(QString(CHEMIN_SERVEUR_NFS) +
`cheminRacineProcessusAssemblage` c'est dans la classe `ProcessusAssemblage` et il faut un accesseur `get`

2024-06-04 15:58 UTC, tvaira commented on ergonomic-workstation-rpi/affichagepageprocessus.cpp
> +    if(fichierHTML.exists())
4 lignes pour faire tout simplement : if(`QFileInfo::exists(fichierHTML)) ...`

Tu m'enlèves les lignes 120 et 121 !

2024-06-04 15:58 UTC, tvaira commented on ergonomic-workstation-rpi/affichagepageprocessus.cpp
> +    QFileInfo fichierHTML = "/processus-assembalge/" + element.fileName() + "/etape" +
`"/processus-assembalge/"` oh !!! déjà il y a une faute de frappe et surtout c'est un attribut de la classe `ProcessusAssemblage` donc on le récupère avec un `get`

2024-06-04 15:58 UTC, tvaira commented on ergonomic-workstation-rpi/affichagepageprocessus.cpp
> +        this->commentairesOperation->setSource(
Toute simplement :

```cpp
this->commentairesOperation->setSource(fichierHTML);
```

2024-06-04 15:58 UTC, tvaira commented on ergonomic-workstation-rpi/affichagepageprocessus.cpp
> +    this->photoOperation->setPixmap(QPixmap(etape->getNomImage()));
Les images sont dans le répertoire `images` !!! Et il faut un chemin.

2024-06-04 15:58 UTC, tvaira commented on ergonomic-workstation-rpi/affichagepageprocessus.cpp
> +void AffichagePageProcessus::etapeSuivante()
Ne sert à rien et en plus il n'y a pas de verbe ! La méthode existe déjà c'est `afficherEtape()` !

2024-06-04 15:58 UTC, tvaira commented on ergonomic-workstation-rpi/affichagepageprocessus.cpp
>      connect(boutonAbandon, SIGNAL(clicked()), this, SLOT(abandonner()));
Il faut les mettre dans un `QVector` comme dans l'ihm !

2024-06-04 19:46 UTC, gavril1 commented on ergonomic-workstation-rpi/affichagepageprocessus.cpp
>      connect(boutonAbandon, SIGNAL(clicked()), this, SLOT(abandonner()));
Je ne comprend pas comment passer d'un étape à l'autre même en les mettant dans un QVector, est ce que vous pouvez m'aider pour ça ?

2024-06-05 02:50 UTC, tvaira commented on ergonomic-workstation-rpi/affichagepageprocessus.cpp
>      connect(boutonAbandon, SIGNAL(clicked()), this, SLOT(abandonner()));
Le "bouton" doit déclencher l'affichage de l'étape suivante ou la fin du processus. Cela se gère dans la méthode `afficherEtape()` :

```cpp
void AffichagePageProcessus::afficherEtape()
{
    // fin de processus ?
    if((numeroEtapeCourante + 1) == nbEtapes)
    {
        this->boutonEtapeSuivante->setText("Terminer");
    }
    else if(numeroEtapeCourante == nbEtapes)
    {
        emit fini(this->nomProcessus->text());
        return;
    }

    // récupère l'étape courante
    etape = processusAssemblage->getEtapes().at(numeroEtapeCourante);

    // affiche l'étape courante
    ...
    
    // prochaine étape ?
    if((numeroEtapeCourante + 1) <= nbEtapes)
    {
        ++numeroEtapeCourante;
    }
}
```

Les deux "boutons" mènent à l'émission de deux signaux qui doivent être connectés et déconnectés dans la classe `IHM` :

```cpp
void IHM::chargerProcessusAssemblage(int numeroProcessus)
{
    ...

    if(processusAssemblage->getNbEtapes() > 0)
    {
        pageProcessus = new AffichagePageProcessus(fenetres, processusAssemblage, dialogueModule);
        connect(pageProcessus,
                SIGNAL(abandon(QString)),
                this,
                SLOT(abandonnerProcessusAssemblage(QString)));
        connect(pageProcessus,
                SIGNAL(fini(QString)),
                this,
                SLOT(terminerProcessusAssemblage(QString)));
        pageProcessus->afficher();
    }
}
```

Les deux slots :

```cpp
void IHM::abandonnerProcessusAssemblage(QString nomProcessus)
{
    disconnect(pageProcessus,
               SIGNAL(abandon(QString)),
               this,
               SLOT(abandonnerProcessusAssemblage(QString)));
    delete pageProcessus;
    // @todo gérer l'abandon d'un processus d'assemblage
    // puis
    afficherFenetreProcessus();
}

void IHM::terminerProcessusAssemblage(QString nomProcessus)
{
    disconnect(pageProcessus,
               SIGNAL(fini(QString)),
               this,
               SLOT(terminerProcessusAssemblage(QString)));
    delete pageProcessus;
    // @todo gérer la fin d'un processus d'assemblage
    // puis
    afficherFenetreProcessus();
}
```

Pour finir, tu dois gérer les deux "boutons" avec l'encodeur. Les deux "boutons" sont conservés dans : `QVector<QPushButton*> boutonsPageProcessus;` et connectés comme ceci :

```cpp
connect(boutonsPageProcessus[ActionPageProcessus::ActionSuivant],
            SIGNAL(clicked()),
            this,
            SLOT(afficherEtape()));
connect(boutonsPageProcessus[ActionPageProcessus::ActionAbandon],
        SIGNAL(clicked()),
        this,
        SLOT(abandonner()));
```

Et les deux actions sont définies dans un `enum` : 

```cpp
enum ActionPageProcessus
{
    ActionSuivant = 0,
    ActionAbandon,
    NbActionsPageProcessus
};
```

2024-06-06 18:01 UTC, tvaira approved these changes

2024-06-07 06:21 UTC, merged